name: app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.0
  gql: ^0.8.0
  graphql_flutter:
    path: ..

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  test: ^1.5.1

flutter:
  uses-material-design: true

dependency_overrides:
  gql: ^0.8.0
  test_api: ^0.2.5
  collection: ^1.14.11
  graphql:
    path: ../../graphql